# See: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9"

services:
  # blueprint application
  blueprint-app:
    container_name: blueprint-app
    # Will use this image name:tag when building
    image: blueprint-app:latest
    build:
      context: .
      target: prod
    env_file:
    - .env
    environment:
      EXAMPLE_ENV: some_value
    command: [
      "python",
      "/app/blueprint/entrypoints/main.py",
    ]
    restart: always
